### ISSUE TITLE
Nixe

### ISSUE THREAD

**Issue by denbur2** [Sh4yen/NixOS-configs#1]

**Comment by Sh4yen** [comment]
Hast du tatsächlich irgendein Problem gepottet? Du hast nichts in der Beschreibung. Oder ist, dass hier nur ein Schrei nach

**Comment by Sh4yen** [comment]
Hast du tatsächlich irgendein Problem gepottet? Du hast nichts in der Beschreibung. Oder ist, dass hier nur ein Schrei nach Aufmerksamkeit?

**Comment by TheFibonacciEffect** [comment]
Deine Gewalt ist nur ein stummer Schrei nach Liebe
Deine Springerstiefel sehnen sich nach Zärtlichkeit
Du hast nie gelernt dich zu artikulieren
Und deine Eltern hatten niemals für dich Zeit

**Comment by TheFibonacciEffect** [comment]
Cool, dass du das teilst by the way :D Irgendwann werde ich auch mal Nix ausprobieren.

**Comment by denbur2** [comment]
ne war nix
